### ISSUE TITLE
‘Waiting’ Task Is Not Clickable

### ISSUE THREAD

**Issue by ThisFungus** [psu/logseq-style-tweaks#2] opened 2022-10-11 04:31 UTC
As seen in the attached video, the 'WAITING' task is not clickable in the same way as the 'TODO' task is.

---
System Version: macOS 12.6 (21G115)
Logseq: Version 0.8.8 (0.8.8)

https://user-images.githubusercontent.com/52507782/194997092-b802cf89-08a4-4d0b-8bd2-abc21c9945d1.mov

**Comment by psu** [comment] 2022-10-11 13:00
This is the default behavior in Logseq and not a bug. 
What would a click on the waiting label result in?

**Comment by ThisFungus** [comment] 2022-10-12 13:38
> This is the default behavior in Logseq and not a bug.
What would a click on the waiting label result in?

Given my vanilla Logseq setup, I presume the default behavior is that a 'Waiting' task is clickable, and the click would change its status to 'Done,' as seen in the attached clip.

In any case, it would be nice if you could make a 'Waiting' task clickable so that the click event results in 'Done' status :-)

https://user-images.githubusercontent.com/52507782/195356670-eb2b451c-a40f-490f-b330-ca1f95580128.mov

**Comment by psu** [comment] 2022-11-07 20:22
Fixed in v2.0.2

**Closed as completed by psu** 2022-11-07 20:22 UTC
Labels: bug

**Comment by ThisFungus** [comment] 2022-11-17 07:48
> Fixed in v2.0.2

Thanks! :-)
